<?php
include_once 'Finery.php';

class BigTrouser extends Finery
{
    public function show()
    {
        print_r('垮裤'.PHP_EOL);
        parent::show(); // TODO: Change the autogenerated stub
    }
}
