<?php
include_once 'Finery.php';

class LeatherShoes extends Finery
{
    public function show()
    {
        print_r('皮鞋'.PHP_EOL);
        parent::show(); // TODO: Change the autogenerated stub
    }
}
