<?php

include_once 'Finery.php';

class Sneakers extends Finery
{
    public function show()
    {
        print_r('破球鞋'.PHP_EOL);
        parent::show(); // TODO: Change the autogenerated stub
    }
}
