<?php
include_once 'Finery.php';

class Tshirts extends Finery
{
    public function show()
    {
        print_r('大T恤'.PHP_EOL);
        parent::show(); // TODO: Change the autogenerated stub
    }
}
