<?php

include_once 'Target.php';
include_once 'Adaptee.php';

class Adapter extends Target
{
    private Adaptee $adaptee;

    public function __construct()
    {
        $this->adaptee = new Adaptee();
    }

    public function request(): void
    {
//        parent::request(); // TODO: Change the autogenerated stub
        $this->adaptee->specificRequest();
    }
}
