<?php

include_once 'Decorator.php';

class ConcreteDecoratorA extends Decorator
{
    private string  $addedState;

    public function operation(): void
    {
        parent::operation(); // TODO: Change the autogenerated stub
        $this->addedState = 'New State';
        print_r('具体装饰对象 A 的操作'.PHP_EOL);
    }
}
