<?php


class ConcreteDecoratorB extends Decorator
{
    public function operation(): void
    {
        parent::operation(); // TODO: Change the autogenerated stub
        $this->addedBehavior();
        print_r('具体装饰对象 B 的操作'.PHP_EOL);
    }

    public function addedBehavior() :void
    {
    }
}
